version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: llms_postgres
    environment:
      POSTGRES_DB: llms_db
      POSTGRES_USER: llms_user
      POSTGRES_PASSWORD: llms_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sample_users.sql:/samples.sql

volumes:
  postgres_data: 