version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: llms-java-postgres
    environment:
      POSTGRES_DB: llms_java_db
      POSTGRES_USER: llms_java_user
      POSTGRES_PASSWORD: llms_java_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: 